### ISSUE TITLE
Search context char bug

### ISSUE THREAD

**Issue by margaretha** [KorAP/Kustvakt#32]
Context "c" is recognized as token instead of char, e.g 
http://localhost:8089/api/v1.0/search?q=Wasser&ql=poliqarp&context=5-c,5-c

results in

<pre>
"context": {
            "left": [
                "token",
                5
            ],
            "right": [
                "token",
                5
            ]
        },
</pre>

**Comment by Akron** [comment]
I think the problem is in Koral. ```token``` and ```char``` are supported only by Krill for left/right contexts - and I think that's fine for KoralQuery. Koral should transform ```t``` to ```token``` etc. I made a patch at https://korap.ids-mannheim.de/gerrit/#/c/KorAP/Koral/+/2319/ . A valid question is, if patterns like ```5-x,3-x``` should transform to left/right contexts as well. at the moment, they are transformed to strings and treated as element contexts.

**Comment by margaretha** [comment]
Fixed in https://github.com/KorAP/Koral/commit/36026a8edab5f6425ace33a90533c4814e990ce3.
